pipeline {
    agent any
    tools {nodejs "nodejs"}

    stages {
        stage('React Build') {
            steps {
                echo "React build start"
                sh 'pwd'
                sh 'npm install --force'
                sh 'CI=false npm run build'
            }
        }

        stage('Docker build') {
            steps {
                sh 'docker build -t nginx-react-image:latest .'
            }
        }

        stage('Docker run') {
            steps {
                sh 'docker ps -f name=nginx-react-container -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -fname=nginx-react-container -q | xargs -r docker container rm'
                sh 'docker run -d --name nginx-react-container -p 80:80 nginx-react-image:latest'
            }
        }
    }
}